# Generated by Django 5.1.6 on 2025-03-24 18:53

import django_extensions.db.fields
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(choices=[('OPEN', 'Open Orders'), ('SHIPPED', 'Shipped Orders')], max_length=10)),
                ('date', models.DateField()),
                ('status', django_fsm.FSMField(default='OPEN', max_length=50, protected=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('type', 'date')},
            },
        ),
    ]
