# Generated by Django 5.1.6 on 2025-03-24 19:02

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=django_fsm.FSMField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=50, protected=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_number', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('FULL_CIRCLE', 'Full Circle'), ('WMS', 'Wms')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.report')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
