# Generated by Django 5.1.6 on 2025-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_report_status_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('OPEN', 'Open Orders'), ('SHIPPED', 'Shipped Orders')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
