# Generated by Django 5.1.6 on 2025-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_report_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('is_manual', False)), fields=('type', 'date'), name='unique_type_date_for_automated'),
        ),
    ]
