version: "3.9"

services:
  web:
    container_name: web
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: bash -c "gunicorn --workers=5 config.wsgi -b 0.0.0.0:8000"